### ISSUE TITLE
Feature Request: Provide ability to specify arguments to the installers

### ISSUE THREAD

**Issue by mosspilot** [Tripwire/chef-tripwire_agent#12]
When installation of the agents requires additional command line options, it would be very useful to have an attribute where we can specify these command line options. Providing this as a list of attributes that we can specify as command line arguments to the installers would be the most flexible.

**Comment by effective-spoons** [comment]
I'll see what I can do with this later in the week. It should be pretty easy to add the additional to both agent installers.

**Comment by mosspilot** [comment]
Closing this issue, as we don't necessarily need it now.
