### ISSUE TITLE
no implicit conversion of nil to string

### ISSUE THREAD

**Issue by trentbullard** [Tripwire/chef-tripwire_agent#7]
when I try to use this cookbook's resources in my own cookbook (using the minimum required java agent properties), I get the above error. I have tried overriding all the attributes using force_default in my cookbook, to no avail. Any suggesstions?

**Comment by trentbullard** [comment]
I fixed this by including 
```
proxy_hostname ""
install_directory node['tripwire_agent']['java']['install_directory']
```
within my tripwire_java_agent block

**Comment by effective-spoons** [comment]
Which OS are you running the cookbook against? I'd love to see some example of how you use the resource and the error so I can reproduce the problem.

**Comment by trentbullard** [comment]
Firstly, thank you for your prompt response. its rare xD  

Its running a win server 2012 r2 kitchen virtualbox vm. As for the implementation, all I did was add ```depends "tripwire_agent", "~> 0.1.0"``` to my metadata file, and had chef generate a new recipe called tripwire, in which i use
```
tripwire_agent_java "install tripwire java agent" do
    installer node['tripwire_agent']['installer']
    console node['tripwire_agent']['java']['console']
    services_password node['tripwire_agent']['java']['services_password']
    proxy_hostname ""
    install_directory node['tripwire_agent']['java']['install_directory']
end
```
  
Initially, without the proxy_hostname and install_directory properties, but then I realized that those two properties were, by default, being assigned nil since I wasn't using the tripwire agent cookbook as a standalone. Once I manually called those properties in the resource block, the nil defaults were correctly being replaced with strings.  

i'm relatively new to this stuff, but i hope that helps

**Comment by effective-spoons** [comment]
If I didn't filter email so well I'd have known the issue was submitted earlier! 

Awesome, what you've provided does help me understand the problem. I wrote the cookbook without a customer to really give me any feedback so I am hoping it covers a lot of your use cases. I intended it to not require the install_directory or proxy_hostname attributes (so they should be nil) unless you need to change them so its weird that it's complaining about them being nil. 

I'll give it a try and see what I might have missed.

**Comment by trentbullard** [comment]
great, and i was actually referring to developers of other products being slow/unresponsive :smile:

**Comment by effective-spoons** [comment]
Reproduced the issue and am looking into why. Thanks for catching the problem!

**Comment by effective-spoons** [comment]
@p4ndepravity I wanted to check in with you to see if the changes resolved your issues or not.

**Comment by trentbullard** [comment]
@effective-spoons my apologies. yes, this is resolved. thank you for your attentiveness.
